= Spring Antora Maven Plugins
:version: 1.0.0-SNAPSHOT

== antora-component-version-maven-plugin

This plugin defines https://books.sonatype.com/mvnref-book/reference/resource-filtering-sect-properties.html[Maven properties] that can be used for generating an https://docs.antora.org/antora/latest/component-version-descriptor/[antora.yml].
The `antora.yml` can be included using the https://gitlab.com/antora/antora-collector-extension[Antora Collector Extension].

* <<_supported_attributes>>
* <<_configuring_spring_antora_yml_maven_plugin>>

=== Supported Attributes

[%header,cols="1s,1,1"]
|===
| Maven Property Name
| Antora Key
| Description

| `antora-component.version`
| https://docs.antora.org/antora/latest/component-version-key/[`version`]
| Generates the Antora version attribute from the Maven version property by, if present, removing `-SNAPSHOT`.

| `antora-component.prerelease`
| https://docs.antora.org/antora/latest/version-facets/#prerelease[`prerelease`]
a| Generates the Antora prerelease attribute from the Maven version property:

* `1.0.0-SNAPSHOT` will result in the prerelease attribute being set to `-SNAPSHOT`
* `1.0.0-M1` will result in the prerelease attribute being set to `true`
* `1.0.0-RC1` will result in the prerelease attribute being set to `true`
* `1.0.0` will result in the prerelease attribute being set to `false`
|===

=== Configuring antora-component-version-maven-plugin

This section describes how to configure and use the `antora-component-version-maven-plugin`.

To start, define the plugin in your build:

.pom.xml
[source,xml,subs=+attributes]
----
<plugin>
    <groupId>io.spring.maven.antora</groupId>
    <artifactId>antora-component-version-maven-plugin</artifactId>
    <version>{version}</version>
    <executions>
        <execution>
            <id>antora-component-version</id>
            <goals>
                <goal>antora-component-version</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

Second, ensure that https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html[Maven Filtering] is enabled:

.pom.xml
[source,xml]
----
<resources>
    <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
    </resource>
</resources>
----

Next, create a resource that will be filtered with the properties added by the plugin:

.src/main/resources/antora-resources/antora.yml
[source,yml]
----
version: ${antora-component.version}
prerelease: ${antora-component.prerelease}
asciidoc:
  attributes:
    attribute-missing: 'warn'
# ... more attributes (possibly with values from other properties) as needed ...
----

Finally, you can generate the resource by invoking `process-resources`:

[source,bash]
----
$ mvn process-resources; cat target/classes/antora-resources/antora.yml
...
version: 1.0.0
prerelease: -SNAPSHOT
asciidoc:
  attributes:
    attribute-missing: 'warn'
----

To use this with the Antora Collector Extension, you need to define the command in the collector configuration.
For example:

.antora.yml
[source,yml]
----
name: data-commons
version: true
title: Spring Data Commons
nav:
  - modules/ROOT/nav.adoc
ext:
  collector:
    - run:
        command: mvnw -Pdocs process-resources
        local: true
      scan:
        dir: target/classes/antora-resources
----

