= Spring Antora Maven Plugins
:version: 1.0.0-SNAPSHOT

== antora-component-version-maven-plugin

This plugin defines https://books.sonatype.com/mvnref-book/reference/resource-filtering-sect-properties.html[Maven properties] that can be used for generating an https://docs.antora.org/antora/latest/component-version-descriptor/[antora.yml].
The `antora.yml` can be included using the https://gitlab.com/antora/antora-collector-extension[Antora Collector Extension].

* <<antora-component-version-attributes>>
* <<antora-component-version-configuring>>

[[antora-component-version-attributes]]
=== antora-component-version-maven-plugin Supported Attributes

[%header,cols="1s,1,1"]
|===
| Maven Property Name
| Antora Key
| Description

| `antora-component.version`
| https://docs.antora.org/antora/latest/component-version-key/[`version`]
| Generates the Antora version attribute from the Maven version property by, if present, removing `-SNAPSHOT`.

| `antora-component.prerelease`
| https://docs.antora.org/antora/latest/version-facets/#prerelease[`prerelease`]
a| Generates the Antora prerelease attribute from the Maven version property:

* `1.0.0-SNAPSHOT` will result in the prerelease attribute being set to `-SNAPSHOT`
* `1.0.0-M1` will result in the prerelease attribute being set to `true`
* `1.0.0-RC1` will result in the prerelease attribute being set to `true`
* `1.0.0` will result in the prerelease attribute being set to `false`
|===

[[antora-component-version-configuring]]
=== Configuring antora-component-version-maven-plugin

This section describes how to configure and use the `antora-component-version-maven-plugin`.

To start, define the plugin in your build:

.pom.xml
[source,xml,subs=+attributes]
----
<plugin>
    <groupId>io.spring.maven.antora</groupId>
    <artifactId>antora-component-version-maven-plugin</artifactId>
    <version>{version}</version>
    <executions>
      <execution>
        <goals>
          <goal>antora-component-version</goal>
        </goals>
      </execution>
    </executions>
</plugin>
----

Next, create a resource that will have https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html[Maven Filtering] performed on it.
The plugin adds the folder `src/main/antora/resources` as a filtered resource by default and we will use that location in our example.
Alternatively, you can explicitly add https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html[Maven Filtering] to any location and place it there.

Here is an example using the default location:

.src/main/antora/resources/antora-resources/antora.yml
[source,yml]
----
version: ${antora-component.version}
prerelease: ${antora-component.prerelease}
asciidoc:
  attributes:
    attribute-missing: 'warn'
# ... more attributes (possibly with values from other properties) as needed ...
----

NOTE: The folder `antora-resources` is used so that the https://gitlab.com/antora/antora-collector-extension[Antora Collector Extension] can import Antora resources without picking up any other resources your project may have (e.g. resources for your Java project).

Finally, you can generate the resource by invoking `process-resources`:

[source,bash]
----
$ mvn process-resources; cat target/classes/antora-resources/antora.yml
...
version: 1.0.0
prerelease: -SNAPSHOT
asciidoc:
  attributes:
    attribute-missing: 'warn'
----

To use this with the Antora Collector Extension, you need to define the command in the collector configuration.
For example:

.antora.yml
[source,yml]
----
name: data-commons
version: true
title: Spring Data Commons
nav:
  - modules/ROOT/nav.adoc
ext:
  collector:
    - run:
        command: mvnw -Pdocs process-resources
        local: true
      scan:
        dir: target/classes/antora-resources
----


== antora-maven-plugin

A Maven Plugin (similar to the https://docs.antora.org/gradle-plugin/latest/[Gradle Antora Plugin]) that leverages https://github.com/mojo-executor/mojo-executor[mojo-executor] to dynamically setup and invoke the necessary Maven plugins to setup and run Antora from a Maven build.

[[antora-maven-plugin-attributes]]
=== antora-maven-plugin Supported Attributes

[%header,cols="1s,1,2a"]
|===
| Maven Property Name
| Description
| Example

| `<version>`
| The version of Antora to use. Default is `3.2.0-alpha.2`
|
.pom.xml
[source,xml]
----
<configuration>
  <environment>
    <version>3.1.4</version>
  </environment>
</configuration>
----

| `environment`
| The optional environment element that contains additional environment variables.
|
.pom.xml
[source,xml]
----
<configuration>
  <environment>
    <SEARCH_API_KEY>12346</SEARCH_API_KEY>
    <GOOGLE_ANALYTICS_KEY>abcxyz</GOOGLE_ANALYTICS_KEY>
  </environment>
</configuration>
----

| `options`
| The optional environment element that contains additional Antora CLI options.
The Default is `--to-dir=target/antora/site`, `--stactrace`
|
.pom.xml
[source,xml]
----
<configuration>
  <options>
    <option>--log-failure-level=warn</log-failure-level>
  </options>
</configuration>
----

| `playbook`
| The Antora Playbook to use
The Default is `antora-playbook.yml`
|
.pom.xml
[source,xml]
----
<configuration>
  <options>
    <playbook>src/main/antora/antora-playbook.yml</playbook>
  </options>
</configuration>
----

| `packages`
| The optional property that specifies any additional Node.js Antora and Asciidoctor extension packages the plugin should install.
The Default is `antora-playbook.yml`
|
.pom.xml
[source,xml]
----
<configuration>
  <packages>
    <package>@springio/asciidoctor-extensions@1.0.0-alpha.9</package>
  </packages>
</configuration>
----
|===


[[antora-configuring]]
=== Configuring antora-maven-plugin

This section describes how to configure and use the `antora-maven-plugin`.

To start, define the plugin in your build within the root of a folder that contains your Antora files:

.pom.xml
[source,xml,subs=+attributes]
----
<plugin>
    <groupId>io.spring.maven.antora</groupId>
    <artifactId>antora-maven-plugin</artifactId>
    <version>{version}</version>
    <executions>
        <execution>
            <id>antora</id>
            <goals>
                <goal>antora</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

You can now invoke Antora using `antora:antora` and view the results:

[source,bash]
----
$ mvn antora:antora
...
# view the results
$ tree target/antora/site -P '*.html'
├── _
│   ├── css
│   ├── font
│   ├── img
│   └── js
│       └── vendor
└── test
    └── 1.0.0-SNAPSHOT
        └── index.html
----
